// <auto-generated />
using MVC_8.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVC_8.Models.Home.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            Name = "Åsa Bildt",
                            Phone = "313445"
                        },
                        new
                        {
                            Id = 2,
                            City = "Hällekis",
                            Name = "Olle Zackow",
                            Phone = "259064"
                        },
                        new
                        {
                            Id = 3,
                            City = "Töreboda",
                            Name = "Beda Carlsson",
                            Phone = "709594"
                        },
                        new
                        {
                            Id = 4,
                            City = "New York",
                            Name = "Adrian Fahlgren",
                            Phone = "358458"
                        },
                        new
                        {
                            Id = 5,
                            City = "Skulltorp",
                            Name = "Lotta Erixon",
                            Phone = "994159"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
